### ISSUE TITLE
Config files are not being generated at runtime if they do not exist

### ISSUE THREAD

**Issue by twinsdgc** [TheCricket/ChirpBot-Issues#1]
so i ran the startbot.bat and command prompt shows up then closes.

**Comment by TheCricket** [comment]
can you run it from console and give me a log

**Comment by twinsdgc** [comment]
how do i run from console?

**Comment by TheCricket** [comment]
The commands in the bat

**Comment by twinsdgc** [comment]
i ran that and all it does is pop up then closes it self

**Comment by TheCricket** [comment]
No, Dont run the bat, Run the command thats in the bat in a console window

**Comment by twinsdgc** [comment]
i cant get the command from the bat it closes to fast

**Comment by TheCricket** [comment]
well open it in a text editor

**Comment by twinsdgc** [comment]
i got this as a response http://imgur.com/a/RqaDd

**Comment by TheCricket** [comment]
The jar isnt in that folder

**Comment by twinsdgc** [comment]
yes it is http://imgur.com/a/4UmCR

**Comment by TheCricket** [comment]
Thats a different folder

**Comment by twinsdgc** [comment]
ok so i need to put it some where else?

**Comment by TheCricket** [comment]
just open the console in that folder

**Comment by twinsdgc** [comment]
how do i do that?

**Comment by TheCricket** [comment]
http://bfy.tw/9TzO

**Comment by twinsdgc** [comment]
here is what i says when i run it http://imgur.com/a/41FP3

**Comment by TheCricket** [comment]
Thank you

**Comment by twinsdgc** [comment]
yep

**Comment by twinsdgc** [comment]
so what do i do?

**Comment by TheCricket** [comment]
Fixed and update is released
